spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
              client-id: ${KAKAO_CLIENT_ID}
              client-secret: ${KAKAO_CLIENT_SECRET}
              scope: account_email,name
              client-name: kakao
              redirect-uri: ${KAKAO_REDIRECT_URI}
              client-authentication-method: client_secret_post
              authorization-grant-type: authorization_code
server:
  port: 9090
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret: ${JWT_SECRET}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  h2:
    console:
      path: /h2-console
      enabled: true
server:
  servlet:
    context-path: /api
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
jwt:
  secret: /Cuqu8Ncb4SBniPiFevy/QIn0rAw/zuppXmo67OdHY3wkglglWcYCgFflWBkiq4L